[package]
name = "packed_bits"
description = "Memory-efficient bit packing library"
keywords = ["bit-packing", "embedded", "no-std", "memory-efficient", "macro"]
categories = ["embedded", "no-std", "data-structures"]
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = []
std = []
derive = ["dep:packed_bits_derive"]

[dependencies]
paste.workspace = true
static_assertions.workspace = true
packed_bits_derive = { workspace = true, optional = true }

[dev-dependencies]
trybuild.workspace = true
packed_bits_derive.workspace = true