[workspace]
resolver = "3"
members = ["packed_bits", "packed_bits_derive"]

[workspace.package]
authors = ["Samuel Onoja <0@sami.cx>"]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
paste = "1.0"
static_assertions = "1.0"
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
trybuild = "1.0"
packed_bits_derive = { path = "packed_bits_derive" }
